# Generated by Django 4.2.7 on 2024-02-20 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("neighbour", models.ManyToManyField(to="main.district")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecializationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "specialization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.specialization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("from_price", models.IntegerField(blank=True, null=True)),
                ("to_price", models.IntegerField(blank=True, null=True)),
                (
                    "price_type",
                    models.CharField(
                        blank=True,
                        choices=[("SUM", "sum"), ("DOLLAR", "Dollar"), ("EURO", "Euro")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "part_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FOR_fOUR_HOURS", "От 4 часов в день"),
                            ("PART_DAY", "Неполный день"),
                            ("IN_EVENINGS", "По вечерам"),
                            ("ON_WEEKDAYS", "По выходным"),
                            ("ONE_TIME_TASK", "Разовое задание"),
                        ],
                        max_length=31,
                        null=True,
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        choices=[
                            ("FULL_DAY", "Полный день"),
                            ("SHIFT_SH", "Сменный график "),
                            ("REMOTE", "Удаленная работа"),
                            ("SHIFT_M", "Вахтовый метод"),
                            ("FLEXIBLE", "Гибкий график"),
                        ],
                        max_length=31,
                    ),
                ),
                ("district", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.district")),
                ("experience", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.experience")),
                ("industry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.industry")),
                ("saved", models.ManyToManyField(related_name="saved_vacancy", to=settings.AUTH_USER_MODEL)),
                (
                    "specialization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.specializationtype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.region"),
        ),
    ]
