# Generated by Django 4.2.7 on 2024-02-20 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_task_taskvalue"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpecializationType",
            new_name="Job",
        ),
        migrations.RenameField(
            model_name="vacancy",
            old_name="specialization",
            new_name="job",
        ),
    ]
