# Generated by Django 4.2.7 on 2024-02-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_district_region_alter_job_specialization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="vacancy",
        ),
        migrations.RemoveField(
            model_name="taskvalue",
            name="task",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="job",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="specialization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="main.specialization",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskValue",
        ),
        migrations.AddField(
            model_name="specialization",
            name="tags",
            field=models.ManyToManyField(related_name="specializations", to="main.tag"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="tags",
            field=models.ManyToManyField(related_name="vacancies", to="main.tag"),
        ),
    ]
