# Generated by Django 4.2.7 on 2024-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_skills_remove_vacancy_district_remove_vacancy_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="publish_type",
            field=models.CharField(
                choices=[
                    ("PUBLISH_NOW", "Опубликовать сейчас"),
                    ("PUBLISH_ON_SCHEDULE", "Опубликовать по расписанию"),
                ],
                default="PUBLISH_NOW",
                max_length=63,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="published_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
