# Generated by Django 4.2.7 on 2024-02-21 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_specialization_specialization_parent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
